apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx
  namespace: kube-public
spec:
  controller: {{ .Values.controller.name }}
  parameters:
    apiGroup: k8s.example.com
    kind: IngressParameters
    name: {{ .Values.controller.ingressClass }}